// Copyright 2008-2019 Monetate, Inc.
// 2019-01-07T08:34:01Z t1546849787 sainsburys_entry_masks_only.js
(function(){var g=this;function k(a,c){var d=a.split("."),b=g;d[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+d[0]);for(var e;d.length&&(e=d.shift());)d.length||void 0===c?b[e]&&b[e]!==Object.prototype[e]?b=b[e]:b=b[e]={}:b[e]=c}function l(a){a=a.split(".");for(var c=g,d=0;d<a.length;d++)if(c=c[a[d]],null==c)return null;return c};function n(a){a instanceof Array&&(a=a.join(""));a=Error(a||"");a.name="mtAssert";throw a;};var p="0",q="sainsburys.co.uk",r="!!!",t="sainsburys.co.uk!!!www.sainsburys.co.uk".split(r);p=String(p);q=String(q);r=String(r);function u(){return"https:"==document.location.protocol?"https://sb.monetate.net":"http://b.monetate.net"};var v=[];function w(a,c){var d=x(a,c);k("monetate."+a,d);return d}function x(a,c){var d=l("monetate."+a)||c;"undefined"==typeof d&&(d={});return d};function y(a){var c=document.createElement("script");c.type="text/javascript";c.src=a;c.charset="utf-8";return c}function z(a){var c=document.getElementsByTagName("script")[0];a=y(a);a.async=!0;c.parentNode.insertBefore(a,c);return a};var aa={"~":!0,"!":!0,"*":!0,"(":!0,")":!0,"-":!0,_:!0,".":!0,",":!0,":":!0,"@":!0,$:!0,"'":!0,"/":!0};function ba(a){if(/^[A-Za-z0-9_\-]*$/.test(a))return a;a=a.replace(/([^A-Za-z0-9_\-])/g,function(a,d){return aa[d]?d:encodeURIComponent(d)});return a.replace(/%20/g,"+")};function A(a){for(var c=(document.cookie||"").split(/\s*;\s*/),d=0,b=c.length;d<b;d++){var e=c[d],f=e.indexOf("=");if(-1!=f&&a===e.substring(0,f))return unescape(e.substring(f+1))}return null}function B(a,c,d){var b=q;d=d&&Math.min(d,31536E7);document.cookie=a+"="+ba(c)+"; "+(b&&b.length?"domain="+b+"; ":"")+"path=/; "+(d?"expires="+(new Date((new Date).getTime()+d)).toGMTString()+"; ":"")};var C=w("p",{c:!1,keys:{},ops:[],admits:{}});
function ca(){var a=da;return function(c){for(var d=[],b=0;b<arguments.length;++b)d[b]=arguments[b];b=x("preview",-1);var e=D("preview","mt.ps");if(-1!=b&&e=="cp"+b.cp)a:{b=b.name;for(e=0;e<C.ops.length;e++){var f=C.ops[e];if("mt.ps"==f.cookie&&f.label==b)break a}C.ops.push({cookie:"mt.ps",label:b})}else if(e&&-1==b&&(b=/^([a-z]{1,3})([0-9A-Z]{32})$/.exec(e))&&3==b.length&&(b=u()+("/js/2/a-e7a83e6a/p/sainsburys.co.uk.shop.gb.groceries/entry.js?"+b[1]+"="+b[2]),!C.admits["/js/2/a-e7a83e6a/p/sainsburys.co.uk.shop.gb.groceries/entry.js"])){for(e=0;e<
v.length;e++){var h=v[e].split("."),m=window;for(f=0;f<h.length-1;f++)m=m[h[f]];delete m[h[f]]}v.length=0;e=y(b);e.setAttribute("id","monetate-block");f=document.createElement("div");f.appendChild(e);document.write(f.innerHTML);document.getElementById("monetate-block")?e.removeAttribute("id"):e=void 0;if(e||z(b)){C.admits["/js/2/a-e7a83e6a/p/sainsburys.co.uk.shop.gb.groceries/entry.js"]=!0;return}}a.apply(this,d)}}
function D(a,c){if(!C.c){var d=window.location,b=d.hash;C.c=!0;if(b&&"#monetate-"==b.substr(0,10)){b=b.slice(10).split(",");for(var e=0;e<b.length;e++){var f=b[e].split("=");C.keys[f[0]]=f[1]||"1"}"pushState"in window.history&&window.history.pushState("",document.title,d.protocol+"//"+d.hostname+d.pathname+d.search)}}a in C.keys&&B(c,C.keys[a]);return A(c)};var E=null;function F(){null===E&&(E=!!D("diagnostics","mt.diagnostics"))&&(G("a","a-e7a83e6a/p/sainsburys.co.uk.shop.gb.groceries"),G("ts","f.monetate.net"));return E}var ea=w("dq",[]);function G(a,c){F()&&ea.push({type:a,obj:c})}function H(a,c,d,b,e){G(d?"h":"hi",{name:b||a,timeout:4E3,css:c,selector:b,actionId:e})};var fa=w("rp",[]);k("monetate.rph",function(a,c){fa.push({data:a,callback:c})});function J(a){var c=x("rph");c&&c(a,void 0)}function K(a,c){a.e=a.e||[];-1===a.e.indexOf(c)&&a.e.push(c)};var L={trace:function(){}};var M=0;function N(a){if(3>M){M+=1;!a.msg&&a.entry&&(a.msg=a.entry);G("e",a);var c={};K(c,"xx");c.xx=c.xx||[];c.xx.push(a);J(c)}}function O(a,c){return function(d){for(var b=[],e=0;e<arguments.length;++e)b[e]=arguments[e];try{return c.apply(this,b)}catch(f){try{L.trace({e:f}),N({entry:a,xname:f.name,xmsg:f.message,msg:a})}catch(h){L.trace({e:f})}}}}function P(a,c){return setTimeout(O("timeout",a),c)};/*
 Sizzle CSS Selector Engine v2.3.4-pre
 https://sizzlejs.com/

 Copyright JS Foundation and other contributors
 Released under the MIT license
 https://js.foundation/

 Date: 2017-09-01
*/
function ha(a){for(var c=0;c<a.length;c++)if(!ia(a[c]))return!1;return!0}
function ia(a){var c=new RegExp(a.value,"i"),d=window.location;switch(a.op){case "path_iregex":if(!c.test(d.pathname))return!1;break;case "url_iregex":if(!c.test(d.protocol+"//"+d.hostname+d.pathname))return!1;break;case "full_iregex":if(!c.test(d.protocol+"//"+d.hostname+d.pathname+d.search))return!1;break;case "not_param_iequals":if((a=document.location.search.match(new RegExp("(#|\\?|&)"+a.value+"=(.*?)(&|$)","i")))&&a[2]&&decodeURIComponent(a[2].replace(/\+/g," ")))return!1;break;default:return N({entry:"mask",
msg:"mask",xmsg:"Unknown rule: "+a.op}),!1}return!0};var Q=w("st",{refs:{},id:0,last:"",defer:!1});
function R(){var a={},c="";for(b in Q.refs)if(Q.refs.hasOwnProperty(b)){var d=Q.refs[parseInt(b,10)];a[d]||(c+=d+"\n",a[d]=!0)}if(Q.last!=c&&(Q.last=c,(a=document.getElementById("monetatecss"))&&a.parentNode.removeChild(a),c)){/MSIE [6789]\./.test(navigator.userAgent)&&document.styleSheets&&31<=document.styleSheets.length&&n("stylesheet limit reached");(a=document.getElementsByTagName("head")[0])||n("missing <head>");var b=document.createElement("style");b.setAttribute("type","text/css");b.styleSheet?
b.styleSheet.cssText=c:b.appendChild(document.createTextNode(c));b.id="monetatecss";a.insertBefore(b,a.firstChild)}};var S=[],T=0,U={},V=null;function W(a){var c=U[a]||0;c+=1;return U[a]=c}function X(){var a=x("timeBasis",null);null===a&&(a=window.monetateT||(new Date).getTime(),k("monetate.timeBasis",a),Y({n:"basis",s:W("basis"),t:-X(),d:0}));return a}function ja(a){a&&(a.d=(new Date).getTime()-X()-a.t,Y(a))}
function ka(){if(null===V){var a;if(!(a=F()))a:{a=A("mt.v");a&&64>a.length||(a="2."+Math.floor(2147483647*Math.random())+"."+(new Date).getTime(),B("mt.v",a,15768E7));if(a&&(a=a.split("."))&&1<a.length&&(a=a[1])&&a.length){a=1>parseInt(a,10)%100;break a}a=!1}V=a}return V}function la(){var a=ca();return function(c){for(var d=[],b=0;b<arguments.length;++b)d[b]=arguments[b];b=ka()?{n:"entry",s:W("entry"),t:(new Date).getTime()-X()}:null;try{return a.apply(window,d)}finally{ja(b)}}}
function Y(a){G("m",a);S.push(a);1==S.length&&P(ma,750)}function ma(){if(10>T){T+=1;var a={},c=S;K(a,"xt");a.xt=c;J(a)}S=[]};var Z=w("em",{masks:{},count:0,tmark:null});function na(a,c){if(!Z.masks[a]){Z.count++;if(!Z.tmark&&ka()){var d={n:"mask",s:W("mask"),t:(new Date).getTime()-X()};Z.tmark=d}d=c+" { visibility: hidden !important; } \n";var b=Q.id++;d&&(Q.refs[b]=d,Q.defer||R());b={extended:!1,stylesheetId:b,selector:c,key:a,onRemove:void 0};Z.masks[a]=b;c&&(Z.masks[c]=b);H(a,d,!0,c,a&&!isNaN(a)?+a:null)}}
function oa(a){var c=void 0;if(a.rules&&ha(a.rules))for(c||(c=P(function(){var a=[];for(d in Z.masks)if(Z.masks.hasOwnProperty(d)){var c=Z.masks[d];Z.masks[d].extended&&-1===a.indexOf(c.key)&&a.push(c.key)}var d=0;for(c=a.length;d<c;d++)N({entry:"mask",msg:"extended mask not removed",xmsg:"Action ID: "+a[d]+" extended a mask without removing it"});for(var h in Z.masks)if(Z.masks.hasOwnProperty(h)&&(a=Z.masks[h])){d=a.stylesheetId;Q.refs[d]&&(delete Q.refs[d],Q.defer||R());if(a.onRemove)a.onRemove();
delete Z.masks[a.key];delete Z.masks[a.selector];Z.count--;Z.tmark&&0===Z.count&&ja(Z.tmark)}},4E3)),c=0;c<a.action_ids.length;c++)na(a.action_ids[c]+"",a.selector);else if(F())for(c=0;c<a.action_ids.length;c++){var d=a.action_ids[c]+"";H(d,a.selector+" { visibility: hidden !important; } \n",!1,a.selector,d&&!isNaN(d)?+d:null)}}function pa(){for(var a=x("masks",[]),c=0,d=a.length;c<d;++c){var b=a[c];O("masks",function(){oa(b)})()}};var qa=/MSIE\ (?:[6-9]|10\.)|Trident\/|Version\/(?:3\.[1-2]|[4-9]|1[0-9]).*Safari|Firefox\/|Chrome|CriOS\/|Windows\s?NT\s?10\.0|AppleWebKit\/.*Mobile\//,ra=[],sa=/Firefox\/(?:1\.0)|Windows CE|Google-HotelAdsVerifier/;function ta(){var a=ua();return function(c){for(var d=[],b=0;b<arguments.length;++b)d[b]=arguments[b];b=window.location.protocol;"http:"!=b&&"https:"!=b||a.apply(this,d)}}
function ua(){var a=va();return function(c){for(var d=[],b=0;b<arguments.length;++b)d[b]=arguments[b];b=navigator;"1"!=p||"1"!=b.doNotTrack&&"yes"!=b.doNotTrack&&"1"!=b.msDoNotTrack?a.apply(this,d):B("mt.v","",-1)}}function va(){var a=wa();return function(c){for(var d=[],b=0;b<arguments.length;++b)d[b]=arguments[b];b=navigator.userAgent;var e=qa.test(b);if(!e)for(var f=0,h=ra.length;f<h;f++)if(ra[f].test(b)){e=!0;break}e&&!sa.test(b)&&a.apply(this,d)}}
function wa(){var a=la();return function(c){for(var d=[],b=0;b<arguments.length;++b)d[b]=arguments[b];a:{b=document.location.host;for(var e=0,f=t.length;e<f;e++){var h=t[e],m;if(!(m=b==h)){m="."+h;var I=b.length-m.length;m=0<=I&&b.indexOf(m,I)==I}if(m){b=h;break a}}b=q}b||n("Cookie domain is null or undefined");q=b;a.apply(this,d)}};var xa=!1;function da(){xa&&pa();var a=x("preview",-1);var c=D("preview","mt.ps");a=-1!=a&&c=="cp"+a.cp?"?cp="+a.cp:"";z((a?u():"https:"==document.location.protocol?"https://se.monetate.net":"http://e.monetate.net")+("/js/3/a-e7a83e6a/p/sainsburys.co.uk.shop.gb.groceries/t1546849787/7bfcfa39dc5dcd96/custom.js"+a))};if(!/ANALYTICS-EXCLUDED/.test(navigator.userAgent)){xa=!0;var ya=O("entry",ta());l("monetate.entry")||(v.push("monetate.entry"),k("monetate.entry",ya))};}).call(this);
if(this.monetate){monetate.redirect=[];monetate.masks=[{"action_id":2675816,"action_ids":[2675816,2675817],"rules":[{"op":"path_iregex","value":"^\\/shop\\/"}],"selector":"#groceriesNav > div.mainNavBlock > ul.mainNav > li.mainNavItem > a.mainNavLink"}];monetate.tgt=[{"args":["utag.data.user_id","",""],"is_collector":false,"is_id":true,"op":"targetJSVar","rules":{"op":"","value":""},"targetId":41285}];monetate.bk=false;monetate.preview=null;monetate.ch="75bc4abb2a8e37e0";monetate.entry()}