//tealium universal tag - utag.65 ut4.0.201901101231, Copyright 2019 Tealium.com Inc. All Rights Reserved.
if(typeof JSON!=='object'){JSON={};}
(function(){'use strict';var rx_one=/^[\],:{}\s]*$/,rx_two=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,rx_three=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,rx_four=/(?:^|:|,)(?:\s*\[)+/g,rx_escapable=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,rx_dangerous=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;function f(n){return n<10?'0'+n:n;}
function this_value(){return this.valueOf();}
if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+
f(this.getUTCMonth()+1)+'-'+f(this.getUTCDate())+'T'+f(this.getUTCHours())+':'+f(this.getUTCMinutes())+':'+
f(this.getUTCSeconds())+'Z':null;};Boolean.prototype.toJSON=this_value;Number.prototype.toJSON=this_value;String.prototype.toJSON=this_value;}
var gap,indent,meta,rep;function quote(string){rx_escapable.lastIndex=0;return rx_escapable.test(string)?'"'+string.replace(rx_escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
if(typeof rep==='function'){value=rep.call(holder,key,value);}
switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
v=partial.length===0?'[]':gap?'[\n'+gap+partial.join(',\n'+gap)+'\n'+mind+']':'['+partial.join(',')+']';gap=mind;return v;}
if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){if(typeof rep[i]==='string'){k=rep[i];v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
if(typeof JSON.stringify!=='function'){meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
return str('',{'':value});};}}());try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'all':1};u.server_domain="tealiumiq.com";u.server_prefix="";u.tag_config_server="";u.tag_config_sampling="100"||"100";if(utag.cfg.utagdb){u.tag_config_sampling="100";}
u.tag_config_region="eu-west-1"||"default";u.region="";u.performance_timing_count=0;u.account=utag.cfg.utid.split("/")[0];u.data_source="";u.profile=""||utag.cfg.utid.split("/")[1];if(u.tag_config_server.indexOf("-collect."+u.server_domain)>1){u.server_prefix=u.tag_config_server.split("collect."+u.server_domain)[0];if(u.tag_config_server.indexOf("/i.gif")<0){u.tag_config_server="https://"+[u.server_prefix+"collect."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}}
if(u.tag_config_server===""){if(u.tag_config_region==="default"){u.tag_config_server="https://"+[u.server_prefix+"collect."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}else{u.tag_config_server="https://"+[u.server_prefix+"collect-"+u.tag_config_region+"."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}}
if(u.tag_config_region!=="default"&&u.tag_config_server.indexOf(u.server_prefix+"collect."+u.server_domain)>0){u.tag_config_server=u.tag_config_server.replace(u.server_prefix+"collect."+u.server_domain,u.server_prefix+"collect-"+u.tag_config_region+"."+u.server_domain);u.region=u.tag_config_region;}
u.data_enrichment="none";u.profile_specific_vid=0;u.enrichment_polling=1;u.enrichment_polling_delay=1000;u.do_enrichment=function(){};var q=u.tag_config_server.indexOf("?");if(q>0&&(q+1)==u.tag_config_server.length){u.tag_config_server=u.tag_config_server.replace("?","");}
u.server_list=u.tag_config_server.split("|");u.enrichment_enabled={};u.get_account_profile=function(s){var p=s.substring(s.indexOf(u.server_domain)).split("/");return p;}
u.is_in_sample_group=function(b){var group="100";if(u.tag_config_sampling===""||u.tag_config_sampling==="100"){return true}
if(b["cp.utag_main_dc_group"]){group=b["cp.utag_main_dc_group"];}else{group=Math.floor(Math.random()*100)+1;utag.loader.SC("utag_main",{"dc_group":group});}
if(parseInt(group)<=parseInt(u.tag_config_sampling)){return true}else{return false}}
u.get_performance_timing=function(b){var t,timing;var data={};function subtract(val1,val2){var difference=0;if(val1>val2){difference=val1-val2;}
return difference;}
if(typeof localStorage!="undefined"&&JSON.parse&&window.performance&&window.performance.timing){t=window.performance.timing;timing=localStorage.getItem("tealium_timing");if(timing!==null&&timing!=="{}"&&typeof b!=="undefined"&&u.performance_timing_count===0){utag.ut.merge(b,utag.ut.flatten({timing:JSON.parse(timing)}),1);}}else{return;}
u.performance_timing_count++;for(var k in t){if((k.indexOf("dom")===0||k.indexOf("load")===0)&&t[k]===0&&u.performance_timing_count<20){setTimeout(u.get_performance_timing,1000);}}
data["domain"]=location.hostname+"";data["pathname"]=location.pathname+"";data["query_string"]=(""+location.search).substring(1);data["timestamp"]=(new Date()).getTime();data["dns"]=subtract(t.domainLookupEnd,t.domainLookupStart);data["connect"]=subtract(t.connectEnd,t.connectStart);data["response"]=subtract(t.responseEnd,t.responseStart);data["dom_loading_to_interactive"]=subtract(t.domInteractive,t.domLoading);data["dom_interactive_to_complete"]=subtract(t.domComplete,t.domInteractive);data["load"]=subtract(t.loadEventEnd,t.loadEventStart);data["time_to_first_byte"]=subtract(t.responseStart,t.connectEnd);data["front_end"]=subtract(t.loadEventStart,t.responseEnd);data["fetch_to_response"]=subtract(t.responseStart,t.fetchStart);data["fetch_to_complete"]=subtract(t.domComplete,t.fetchStart);data["fetch_to_interactive"]=subtract(t.domInteractive,t.fetchStart);try{localStorage.setItem("tealium_timing",JSON.stringify(data));}catch(e){utag.DB(e)}}
u.map={};u.extend=[function(a,b){try{if((b['event_name'].toString().toLowerCase()=='addToBasket'.toLowerCase()&&typeof b['event_name']!='undefined'&&b['event_name']!='')||(b['event_name'].toString().toLowerCase()=='firstAddToBasket'.toLowerCase()&&typeof b['event_name']!='undefined'&&b['event_name']!='')){if(typeof digitalData.product=="object"){var i;var id;var productName=[];var pid=b.product_id;var products=digitalData.product;for(i=0;i<products.length;i++){id=products[i].productInfo.productId;if(id==pid){productName.push(products[i].productInfo.productName);}}
b.product_name=productName;if(b._cprodname.length==0){b._cprodname=b.product_name;}}
else{console.log("No digitalData.product");}
var price_array=[];var quantity_array=[];var newEvent=[];var eventInfo;if(typeof digitalData.event[digitalData.event.length-1]=="object"){newEvent=digitalData.event[digitalData.event.length-1];eventInfo=newEvent.eventInfo;}
else if(typeof digitalData.page.events[0]=='object'){eventInfo=digitalData.page.events[0];}
else{eventInfo="";}
if(eventInfo!=""){if(utag.data&&utag.data.page_name!=undefined){b.product_action_list=utag.data.page_name;}
b.ga_product_id_hit=b.product_id[0];var unitPrice;var itemMaxWeight;if(eventInfo.quantityType=="weight"||eventInfo.quantityType=="weight range"){if(eventInfo.weight!==""){quantity_array.push(Math.ceil(eventInfo.weight));price_array.push(Number(eventInfo.itemPrice));}
else{quantity_array.push(eventInfo.quantity);try{itemMaxWeight=Number(eventInfo.weightRange.replace(/^[^-]+-|k?g/g,""));if(/[^k]g+$/.test(eventInfo.weightRange)){itemMaxWeight=itemMaxWeight/1000;}}catch(e){}
price_array.push((Number(eventInfo.itemPrice)*itemMaxWeight).toFixed(2));}}
else{quantity_array.push(eventInfo.quantity);price_array.push(eventInfo.itemPrice);}
b.atb_quantity_array=quantity_array;b.atb_price_array=price_array;try{b.trolley_item_number=document.getElementById("trolleyTableBody").rows.length;}catch(e){}
var searchPos=window.getSearchPosition(eventInfo.productSKU);var positionNumber=[];if(utag.data.search_term){if(searchPos){positionNumber.push(searchPos);b.atb_matrix_position_number=positionNumber;}}
else if(searchPos){positionNumber.push(searchPos);b.atb_matrix_position_number=positionNumber;}}
else{console.log("No ATB eventInfo");}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b['non_interaction']='false'}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(utag.data['dom.query_string']===""){b['ga_clean_url']=b['dom.pathname'];}
else{b['ga_clean_url']=b['dom.pathname']+"?"+b['dom.query_string'].replace(/=([^&]+@[^\.]+)\./g,'=xxx@xxx.');}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_template']=='productDetails'){try{b['review_number']=digitalData.product[0].productAttributes.reviewsNumber;}catch(e){};try{b['review_score']=digitalData.product[0].productAttributes.reviewScore;}catch(e){}}}catch(e){utag.DB(e)}},function(a,b){try{if((b['page_template'].toString().toLowerCase()=='productDetails'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){if(b["ga_pdp_binary"]!="true"){var interval=setInterval(function(){if(typeof digitalData.product=='object'&&digitalData.product.length>0){setProductName();}},1000)}
function setProductName(){var productName=[];productName.push(digitalData.product[0].productInfo.productName);b.product_name=productName;if(utag.data.ga_pdp_event!="true"){b.ga_enh_action="detail";b.ga_event_category='EEC';b.ga_event_action='Product details view';b.non_interaction=true;utag.link(b,null,[79]);clearInterval(interval);b["ga_pdp_binary"]="true";utag.data.ga_pdp_event="true";}}}}catch(e){utag.DB(e)}},function(a,b,c,d,e,f,g){d=b['page_name'];if(typeof d=='undefined')return;c=[{'groceries:delivery:delivery booking':'1'},{'groceries:collect:collection slot booking':'1'},{'groceries:fulltrolley':'2'},{'groceries:checkout:product upsell':'3'},{'groceries:checkout:forgotten your favourites':'4'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['checkout_step']=c[e][f];m=true};};if(m)break};},function(a,b,c,d,e,f,g){d=b['page_event'];if(typeof d=='undefined')return;c=[{'order review':'5'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['checkout_step']=c[e][f];m=true};};if(m)break};},function(a,b,c,d,e,f,g){d=b['page_name'];if(typeof d=='undefined')return;c=[{'groceries:delivery:delivery booking':'checkout'},{'groceries:collect:collection slot booking':'checkout'},{'groceries:fulltrolley':'checkout'},{'groceries:checkout:product upsell':'checkout'},{'groceries:checkout:forgotten your favourites':'checkout'},{'groceries:checkout:order review':'checkout'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['ga_enh_action']=c[e][f];m=true};};if(m)break};},function(a,b,c,d,e,f,g){d=b['event_name'];if(typeof d=='undefined')return;c=[{'addToBasket':'add'},{'firstAddToBasket':'add'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['ga_enh_action']=c[e][f];m=true};};if(m)break};},function(a,b){try{if(1){try{b['intelligentreach_newcustomer']=b.first_order_ref=="New"?true:false;}catch(e){};try{b['intelligentreach_instorepickup']=b.order_shipping_method&&b.order_shipping_method.toLowerCase().indexOf('collect')>-1?true:false;}catch(e){}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['dom.domain'].toString().toLowerCase().indexOf('recipes.sainsburys.co.uk'.toLowerCase())>-1){tealium.jQuery(document).mousedown(function(e){if(typeof b.ga_event_fired==='undefined'&&b['ut.event']=='view'){var promo_name;var promo_id;var promo_creative;var promo_type;var target=e.target;if(target.tagName=="A"||target.tagName=="IMG"||target.tagName=="SPAN"){var atag1=target.closest('a[class^="mini-promo"]');var atag2=target.closest('a[class^="rhs__promo"]');var atag3=target.closest('a[class^="mission"]');var atag4=target.closest('div[class^="mini-promo"]').getElementsByClassName("mini-promo__image")[0];if(atag1||atag2||atag3||atag4){var atag;if(atag1){atag=atag1;}
else if(atag2){atag=atag2;}
else if(atag3){atag=atag3;}
else{atag=atag4;}
promo_name=tealium.jQuery(atag).attr("href").match(/INTCMP=(.*)/)[1];b.promo_name=promo_name;var divContainer;if(atag1||atag4){divContainer=target.closest('div.mini-promo__item');}
else if(atag2){divContainer=target.closest('a.rhs__promo');}
else{divContainer=target.closest('a.mission');}
var creativeTarget;var substring;if(atag1||atag4||atag2){creativeTarget=tealium.jQuery(divContainer).find('img:eq(0)').attr("src");substring=creativeTarget.split('/').slice(3);promo_creative='/'+substring.join('/');}
else{creativeTarget=tealium.jQuery(divContainer).attr("style");substring=creativeTarget.split('/').slice(3);promo_creative='/'+substring.join('/');promo_creative=promo_creative.substring(0,promo_creative.length-1);}
b.promo_creative=promo_creative;if(atag1||atag4){promo_type='mini-promo';}
else if(atag2){promo_type='rhs-promo';}
else if(atag3){promo_type='mission-promo';}
else{promo_type='other-promo';}
var imageName=creativeTarget.split('/').slice(-1)[0].substr(0,creativeTarget.split('/').slice(-1)[0].lastIndexOf('.'));promo_id=promo_type+'>'+imageName;b.espot_reference=promo_id;document.cookie="espot_click="+promo_id+";path=/;domain="+utag.cfg.domain+";expires=";b.ga_event_fired=true;if(utag.data.ga_promo_click!="true"){b.ga_eSpotNamesFinal=[];b.ga_eSpotIdsFinal=[];b.ga_eSpotCreativeFinal=[];b.ga_eSpotRelPositionFinal=[];b.ga_eSpotNamesFinal.push(promo_name);b.ga_eSpotIdsFinal.push(promo_id);b.ga_eSpotCreativeFinal.push(promo_creative);b.event_name='espotclick';utag.data.ga_promo_click="true";utag.link(b,null,[79]);}}}}})}}catch(e){utag.DB(e)}},function(a,b){try{if(b['event_name'].toString().toLowerCase()=='espotclick'.toLowerCase()){var creative=[];var name=[];var id=[];creative.push(b.promo_creative);id.push(b.espot_reference);name.push(b.promo_name);b.ga_promo_creative=creative;b.ga_promo_id=id;b.ga_promo_name=name;}}catch(e){utag.DB(e)}},function(a,b){try{if(b['event_name'].toString().toLowerCase()=='espotclick'.toLowerCase()){b['ga_event_category']='eSpot';b['ga_event_action']='Click';b['ga_event_label']=b['espot_reference']}}catch(e){utag.DB(e)}},function(a,b){try{if((b['espot_event']=='1'&&typeof b['espot_reference']!='undefined'&&b['cp.espot_click'].toString().toLowerCase()!='false'.toLowerCase())){b['ga_event_category']='eSpot';b['ga_event_action']='Next page load';b['ga_event_label']=b['espot_reference']}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_template'].toString().toLowerCase()=='search'.toLowerCase()){if(typeof b.page_secondary_event=='string'&&b.page_secondary_event=='didyoumean'){b.search_category='Did you mean';}
else if(b.search_results==0){b.search_category='No results';}
else{b.search_category='Successful search';}}}catch(e){utag.DB(e)}},function(a,b){try{if((b['meganav_event']=='navigationEntry'&&typeof b['navigation_level']!='undefined'&&typeof b['navigation_taxonomy']!='undefined'&&b['ut.event']=='view')){if(b.ga_extension!='true'){b.ga_events_array=[{eventCategory:"Navigation entry",eventAction:b.navigation_level,eventLabel:b.navigation_taxonomy,nonInteraction:"true"}]
b.non_interaction="true";}else{b.ga_events_array=[]}}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['cp.test_cookie']!='undefined'&&b['cp.test_cookie'].toString().indexOf('false')<0)){b['test_user']=b['cp.test_cookie']}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_event']=='error'||b['page_secondary_event']=='error'||b['event_name']=='wrongVoucher'||b['page_section']=='error'||b['page_template']=='error'||typeof b['error_message']!='undefined'){if(b.ga_extension!='true'){b.ga_events_array=[{eventCategory:"Error",eventAction:"Error",eventLabel:b.error_message}]}else{b.ga_events_array=[]}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_name_identifier'].toString().toLowerCase()=='delivery booking'.toLowerCase()||b['page_name_identifier'].toString().toLowerCase()=='collection slot booking'.toLowerCase()||(typeof b['booking_event']!='undefined'&&b['booking_event'].toString().toLowerCase()=='delivery'.toLowerCase())||b['page_name'].toString().toLowerCase()=='groceries:checkout:order confirmation'.toLowerCase()){b['ga_delivery_location_hashed']=b['delivery_location']}}catch(e){utag.DB(e)}},function(a,b){try{if(typeof b['ga_delivery_location_hashed']!='undefined'){b.ga_delivery_location_hashed=btoa(b.ga_delivery_location_hashed)}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_event'].toString().toLowerCase()=='switch collection'.toLowerCase()||b['page_event'].toString().toLowerCase()=='switch delivery'.toLowerCase()){b['ga_event_category']='Delivery';b['ga_event_action']='Click to switch';b['ga_event_label']=b['page_category']}}catch(e){utag.DB(e)}},function(a,b){try{if(b['booking_event'].toString().toLowerCase()=='collect'.toLowerCase()){b['ga_event_category']='Delivery';b['ga_event_action']='Choose slot';b['ga_event_label']='Collection'}}catch(e){utag.DB(e)}},function(a,b){try{if(b['booking_event'].toString().toLowerCase()=='delivery'.toLowerCase()){b['ga_event_category']='Delivery';b['ga_event_action']='Choose slot';b['ga_event_label']='Home delivery'}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_name'].toString().toLowerCase()=='groceries:collect:collection slot booking'.toLowerCase()){b.ga_event_category="Delivery";b.ga_event_action="Select store location";b.ga_event_label="";if(b.rendering_reference=="mobileweb"){try{var storeName=$(".bookDeliveryAddress").find("p")[0].innerHTML.trim();b.ga_delivery_location_hashed=storeName;}
catch(err){b.ga_delivery_location_hashed="Store name unavailable";}}
else{try{var tag=$(".postcode")[0];var storeName;if(tealium.jQuery(tag).find("a").length==0){storeName=$(".postcode")[0].innerHTML.trim();}
else{storeName=$(".fulfilmentLocation")[0].innerHTML.trim();}
b.ga_delivery_location_hashed=storeName;}
catch(err){b.ga_delivery_location_hashed="Store name unavailable";}}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(typeof b.page_subcategory=='undefined'){b.page_subcategory="(not set)";}
else{b.page_subcategory;}
if(typeof b.page_category=='undefined'){b.page_category="(not set)";}
else{b.page_category;}
if(typeof b.page_subsubcategory=='undefined'){b.page_subsubcategory="(not set)";}
else{b.page_subsubcategory;}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_event'].toString().indexOf('product_zoom')>-1){b.ga_events_array=[{eventCategory:"Click to zoom",eventAction:"Click to zoom",eventLabel:b.zoom_product,}]}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_event'].toString().toLowerCase()=='cancellation'.toLowerCase()){try{b['ga_cancelled_order_revenue']=digitalData.page.events[0].basePrice}catch(e){}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){window.currentLength=0;window.previousLength=0
window.lastObjIdMousedown=null;window.lastEventInfo=null;window.timeForWait=1000;window.numberTryCheckEventExists=0;var fmArrEventTracked=fmArrEventTracked||[];function checkEventExists(numTry){numberTryCheckEventExists++;var containsEvent=false;try{if(numTry!==undefined&&window.numberTryCheckEventExists<=4){setTimeout(function(){window.numberTryCheckEventExists++;containsEvent=(typeof(digitalData.event)!=="undefined"&&digitalData.event.length>0);if(containsEvent){trackingFoodMaestroEvent();}else{checkEventExists(window.numberTryCheckEventExists);}},1000);}}catch(err){console.warn("Tealium extension 184: Error.\n"+err);}}
function trackingFoodMaestroEvent(){try{var ga_event_category="Food Maestro";window.lastEventInfo=digitalData.event[digitalData.event.length-1].eventInfo;window.currentLength=digitalData.event.length;if(window.currentLength>window.previousLength){re=new RegExp('^(fMaestroProfileCreate|fmProfileCreated|fmCreateProfile|fmCreateProfilePopup1Abandoned|fmCreateProfilePopup2Abandoned|fmCreateProfilePopup3Abandoned|fmCreateProfileTermsAndConditions|fmToggleOn|fmToggleOff|fmRHWTermsAndConditions|fmProfileUpdate|fmCreateProfileUnavailable|fmRHWUnavailable|fmEditProfileUnavailable)$');if(re.exec(window.lastEventInfo.eventName)!==null){switch(lastEventInfo.eventName.toLocaleLowerCase()){case"fmprofilecreated":var fm_allergens=null;if("Allergens"in lastEventInfo){fm_allergens=lastEventInfo.Allergens.sort().toString();}
if(fm_allergens===""){fm_allergens="(not set)";}
utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Profile created","ga_event_label":fm_allergens,"fm_allergens":fm_allergens,"fm_profile_status":"Active"});try{tealium.jQuery("#fmCreateProfileTCPopup").on("mousedown",function(e){if(e.which==3){utag.link({"ga_event_category":"Food Maestro","ga_event_action":"Creating profile","ga_event_label":"Pop up 4 - Read terms and conditions"});}});}catch(err){console.warn("Tealium extension 184: Error.\n"+err);}
break;case"fmcreateprofile":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Pop up 1 - open"});break;case"fmcreateprofilepopup1abandoned":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Pop up 1 - abandoned"});break;case"fmcreateprofilepopup2abandoned":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Pop up 2 - abandoned"});break;case"fmcreateprofilepopup3abandoned":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Pop up 3 - abandoned"});break;case"fmcreateprofiletermsandconditions":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Pop up 4 - Read terms and conditions"});break;case"fmprofileupdate":var fm_allergens=null;if("Allergens"in lastEventInfo){fm_allergens=lastEventInfo.Allergens.sort().toString();}
if(fm_allergens===""){fm_allergens="(not set)";}
utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Update profile","ga_event_label":fm_allergens,"fm_allergens":fm_allergens});fm_allergens=null;break;case"fmcreateprofileunavailable":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Food Maestro Unavailable - Pop up 3"});break;case"fmrhwunavailable":var eLabel=lastEventInfo.eventName;if(eLabel=="fmRHWUnavailable"){eLabel="Food Maestro Unavailable";}
utag.link({"ga_event_category":ga_event_category,"ga_event_action":"RHW Unavailable","ga_event_label":eLabel});break;case"fmeditprofileunavailable":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Update profile","ga_event_label":"Food Maestro Unavailable"});break;case"fmrhwunavailable":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Food Maestro Unavailable – RHWU"});break;case"fmeditprofileunavailable":if(!isCloseButton){utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Update profile","ga_event_label":"Food Maestro Unavailable"});}
break;}
fmArrEventTracked.push(lastEventInfo.eventName.toLocaleLowerCase());}}else{re=new RegExp('^(fmCreateProfileUnavailable|fmRHWUnavailable|fmEditProfileUnavailable)$');if(re.exec(window.lastEventInfo.eventName)!==null){switch(lastEventInfo.eventName.toLocaleLowerCase()){case"fmeditprofileunavailable":if(!isCloseButton){utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Update profile","ga_event_label":"Food Maestro Unavailable"});}
break;case"fmrhwunavailable":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Food Maestro Unavailable – RHWU"});break;case"fmeditprofileunavailable":utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Update profile","ga_event_label":"Food Maestro Unavailable"});break;}}else if((window.lastObjIdMousedown.toLocaleLowerCase()=="fmaestroprofilecreate")&&(!tealium.jQuery("#fMaestroErrorMessage").hasClass("hidden"))){utag.link({"ga_event_category":ga_event_category,"ga_event_action":"Creating profile","ga_event_label":"Food Maestro Unavailable – RHWU"});}}}catch(err){console.warn("Tealium extension 184: Error.\n"+err);}}
if(window.tealiumExtensionFMaestro==undefined){tealium.jQuery(document).on("mousedown",function(e){try{if(detectLeftButton(e)){window.lastObjIdMousedown=e.target.id;var isIdentifiedButton=false;var isEditProfileCLick=(e.target.id=="fMaestroProfileEdit");var isCloseButton=false;window.numberTryCheckEventExists=0;var re=new RegExp('^(fMaestroProfileCreate|fmProfileReviewContinueButton|fmCreateProfileTCPopup|fmProfileConditionsSaveButton|fMaestroProfileTC)$');isIdentifiedButton=(re.exec(e.target.id)!==null);window.previousLength=digitalData.event.length;if(!isIdentifiedButton&&!isEditProfileCLick){try{if(e.target.id.toLowerCase()=="fmprofileyesdeletebutton"){utag.link({"ga_event_category":"Food Maestro","ga_event_action":"Profile Deleted","ga_event_label":"","fm_profile_status":"Deleted"});}else{if(window.commonObject.cookies.getCookie("debugger_emc")=="184-1"){debugger}
try{isCloseButton=((e.target.parentElement.parentElement.id.toLowerCase()=="fm_overlaybox")&&(e.target.className.toLowerCase().indexOf("closelink")>-1));}catch(err){isCloseButton=false;}}}catch(err){console.log("Tealium extension 184: Error.\n"+err);}}
window.timeForWait=window.timeForWait||1000;checkEventExists(numberTryCheckEventExists);}else{try{if(e.target.id.toLowerCase()=="fmcreateprofiletcpopup"){utag.link({"ga_event_category":"Food Maestro","ga_event_action":"Creating profile","ga_event_label":"Pop up 4 - Read terms and conditions"});}}catch(err){console.warn("Tealium extension 184: Error.\n"+err);}}}catch(err){console.warn("Tealium extension 184: Error.\n"+err);}});window.tealiumExtensionFMaestro=true;tealium.jQuery("#fMaestroProfileTC").on("click",function(e){try{utag.link({"ga_event_category":"Food Maestro","ga_event_action":"Click to Terms and Conditions","ga_event_label":""});}catch(err){console.warn("Tealium extension 184: Error.\n"+err);}});}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page_name']=='sainsburys:homepage'){b['site_platform']='sainsburys:homepage'}}catch(e){utag.DB(e)}},function(a,b){try{if(b['ut.event'].toString().toLowerCase()=='view'.toLowerCase()){var x,w;var pos;var count;var substring;var eSpotType=[];var eSpots=[];var eSpotIds=[];var eSpotDivIds=[];var eSpotNames=[];var eSpotCreative=[];var eSpotRelPosition=[];var ga_eSpotIdsFinal=[];var ga_eSpotNamesFinal=[];var ga_eSpotCreativeFinal=[];var ga_eSpotRelPositionFinal=[];var exists=false;if(document.location.hostname=="recipes.sainsburys.co.uk"){if(document.getElementsByClassName("mission").length>0){var missionEl=document.getElementsByClassName("mission");for(var i=0;i<missionEl.length;i++){var id,path,creative,name;name="mission-promo";id=missionEl[i].style.backgroundImage.split('/').slice(-1)[0].substr(0,missionEl[i].style.backgroundImage.split('/').slice(-1)[0].lastIndexOf('.'));path=missionEl[i].style.backgroundImage.split('/').slice(3);creative='/'+path.join('/');creative=creative.substring(0,creative.indexOf('")'));ga_eSpotNamesFinal.push(name);ga_eSpotIdsFinal.push(id);ga_eSpotCreativeFinal.push(creative);ga_eSpotRelPositionFinal.push(i+1);}}
if(document.getElementsByClassName("mini-promo__item").length>0){var missionEl=document.getElementsByClassName("mini-promo__item");for(var i=0;i<missionEl.length;i++){var id,path,creative,name;name="mini-promo";var image=missionEl[i].getElementsByTagName("img");id=image[0].src.split('/').slice(-1)[0].substr(0,image[0].src.split('/').slice(-1)[0].lastIndexOf('.'));path=image[0].src.split('/').slice(3);creative='/'+path.join('/');ga_eSpotNamesFinal.push(name);ga_eSpotIdsFinal.push(id);ga_eSpotCreativeFinal.push(creative);ga_eSpotRelPositionFinal.push(i+1);}}
if(document.getElementsByClassName("rhs__promo").length>0){var missionEl=document.getElementsByClassName("rhs__promo");for(var i=0;i<missionEl.length;i++){var id,path,creative,name;name="rhs-promo";var image=missionEl[i].getElementsByTagName("img");id=image[0].src.split('/').slice(-1)[0].substr(0,image[0].src.split('/').slice(-1)[0].lastIndexOf('.'));path=image[0].src.split('/').slice(3);creative='/'+path.join('/');ga_eSpotNamesFinal.push(name);ga_eSpotIdsFinal.push(id);ga_eSpotCreativeFinal.push(creative);ga_eSpotRelPositionFinal.push(i+1);}}}
else if(document.getElementsByClassName("siteCatalystTag").length>0){x=document.getElementsByClassName("siteCatalystTag");var id;var divid;var eSpot_var;var prodEspot;for(var i=0;i<x.length;i++){id=x[i].innerHTML.toLowerCase();eSpots.push(id);var parentDiv=x[i].parentElement;if(eSpots[i]!=""){if(parentDiv.getElementsByClassName("productESpot").length>0){prodEspot=parentDiv.getElementsByClassName("productESpot");for(var j=0;j<prodEspot.length;j++){count=0;exists=false;var el=prodEspot[j].getElementsByTagName("img")[0];eSpot_var=el.src.split('/').slice(-1)[0].substr(0,el.src.split('/').slice(-1)[0].lastIndexOf('.'));for(var k=0;k<eSpotNames.length;k++){if(eSpotIds[k].split(">")[1]==eSpot_var){exists=true;}}
if(exists!=true){eSpotType.push(x[i].id);eSpotIds.push("productEspot>"+eSpot_var);if(typeof x[i].id!='undefined'){divId=x[i].id}
else{divId="noid"}
eSpotDivIds.push(divId);for(var n=0;n<eSpotNames.length;n++){if(eSpotNames[n]=="productESpot"){count=count+1;}}
pos=count+1;eSpotRelPosition.push(pos);substring=el.src.split('/').slice(3);creative='/'+substring.join('/');eSpotCreative.push(creative);eSpotNames.push("productESpot");exists=false;}}}
else if(parentDiv.className.indexOf("Page")==-1&&parentDiv.getElementsByTagName("img").length>0){prodEspot=parentDiv.getElementsByTagName("img");for(var l=0;l<prodEspot.length;l++){count=0;exists=false;if(prodEspot[l].className.indexOf("roundel")==-1&&(prodEspot[l].tagName=='A'||prodEspot[l].parentElement.tagName=='A')){var imgSrc=prodEspot[l].src.split('/').slice(-1)[0].substr(0,prodEspot[l].src.split('/').slice(-1)[0].lastIndexOf('.'));for(var k=0;k<eSpotNames.length;k++){if(eSpotIds[k].split(">")[1]==imgSrc){exists=true;}}
if(exists!=true){eSpotType.push(x[i].id);eSpotIds.push(eSpots[i]+">"+imgSrc);if(typeof x[i].id!='undefined'){divId=x[i].id}
else{divId="noid"}
eSpotDivIds.push(divId);for(var n=0;n<eSpotNames.length;n++){if(eSpotNames[n]==eSpots[i]){count=count+1;}}
pos=count+1;eSpotRelPosition.push(pos);substring=prodEspot[l].src.split('/').slice(3);creative='/'+substring.join('/');eSpotCreative.push(creative);eSpotNames.push(eSpots[i]);exists=false;}}}}}
}}
for(var q=0;q<eSpotIds.length;q++){try{var reg1=RegExp('^[0-9]+$');var reg2=RegExp('-[a-z0-9]{4}-');if(eSpotDivIds[q].indexOf("USA_CUST_NBR")==-1&&eSpotNames[q]!="upsell"&&reg1.test(eSpotNames[q])!=true&&reg2.test(eSpotNames[q])!=true&&eSpotNames[q]!="x-sell"&&eSpotNames[q].indexOf("<")!=0&&eSpotIds[q].indexOf("rating")==-1&&eSpotIds[q].indexOf("great_with")==-1&&eSpotIds[q].indexOf("do_you_need")==-1){ga_eSpotNamesFinal.push(eSpotNames[q]);ga_eSpotIdsFinal.push(eSpotIds[q]);ga_eSpotCreativeFinal.push(eSpotCreative[q]);ga_eSpotRelPositionFinal.push(eSpotRelPosition[q]);}}
catch(e){console.log(q,e)}}
b.ga_eSpotNamesFinal=ga_eSpotNamesFinal;b.ga_eSpotIdsFinal=ga_eSpotIdsFinal;b.ga_eSpotCreativeFinal=ga_eSpotCreativeFinal;b.ga_eSpotRelPositionFinal=ga_eSpotRelPositionFinal;}}catch(e){utag.DB(e)}},function(a,b){try{if(1){try{if(window.getFmToggleValue===undefined){window.getFmToggleValue=function(){var toggleValue="";try{if(tealium.jQuery("#fMaestroSuitabilityToggle").length==1){toggleValue=tealium.jQuery("#fMaestroSuitabilityToggle")[0].innerText;}}catch(err){console.warn("Tealium extension 195: Error.\n"+err);}
return toggleValue;}}}catch(err){console.warn("Tealium extension 195: Error.\n"+err);}
try{if(typeof(window.fMaestroSuitabilityToggleFlag2)=="undefined"&&(window.getFmToggleValue!==undefined)){tealium.jQuery("#fMaestroSuitabilityToggle").on("click",function(e){var ga_event_label=window.getFmToggleValue();if(ga_event_label.toLowerCase()=="on"){ga_event_label="Off";}else{ga_event_label="On";}
utag.link({"ga_event_category":"Food Maestro","ga_event_action":"Toggle","ga_event_label":ga_event_label,"fm_toggle_value":ga_event_label});});window.fMaestroSuitabilityToggleFlag2=true;}}catch(err){console.warn("Tealium extension 195: Error.\n"+err);}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(b["cp.st_nectar"]&&b["cp.st_nectar"]!=="|"){b.nectar_number_added="Yes - Nectar Used";}
else if(b["cp.st_nectar"]===""){b.nectar_number_added="No - Nectar Not Used";}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){delete b['cp.bt_userEmail'];delete b['cp.bt_delSlot'];delete b['cp.st_nectar'];delete b['cp.bt_regDetails'];delete b['cp.redeyeupdate'];delete b['cp.bt_vCode'];delete b['cp.bt_paymentMeth'];delete b['cp.postcode'];}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(b.event_name.toLowerCase().indexOf("remove")>-1||(b.event_name.toLowerCase().indexOf("addtobasket")>-1&&b.product_finding_method.indexOf("trolley")>-1)){b.vendor_redeye_querystring=(function(){try{var bt_baskItems=[],bt_totalItems=0,tdNumber=2,baskTotal;if(b.product_finding_method==="trolley>fulltrolley"||b.page_name_identifier==="fulltrolley"){tdNumber=3;baskTotal=document.querySelector("#content > div.tableContainer.noFlexComponent > table > tfoot > tr:nth-child(2) > td").innerHTML.replace("£","").replace(/^\s+|\s+$/g,'');bt_trolleyItems=document.querySelector("#content > div.tableContainer.noFlexComponent > table").getElementsByTagName("tbody")[0].children;}
else{bt_trolleyItems=document.getElementById("trolleyTableBody").getElementsByTagName("tr");baskTotal=document.getElementById("trolleyTotal").innerHTML.replace("£","").replace(/^\s+|\s+$/g,'');}
for(var i=0;i<bt_trolleyItems.length;i++){if(i<5){var bt_itemQuanTrolley=(function(){var bt_itemQuan=bt_trolleyItems[i].getElementsByTagName("td")[0].getElementsByTagName("li");for(var l=0;l<bt_itemQuan.length;l++){if(bt_itemQuan[l].className=="inTrolley"){return bt_itemQuan[l].innerHTML.match(/\d+/)[0];}}})();var itemInTrolley;if(digitalData.page.pageInfo.rendering==='web'){itemInTrolley=document.getElementById('itemsInTrolley').innerHTML;}
else{itemInTrolley="";}
bt_totalItems=itemInTrolley;var bask_name=bt_trolleyItems[i].getElementsByTagName("td")[1].getElementsByTagName("a")[0].innerText.replace(/<.*>/g,"").replace(/^\s+|\s+$/g,'');var bask_each_item_val=Number(bt_trolleyItems[i].getElementsByTagName("td")[tdNumber].innerHTML.replace(/<.*>/g,"").replace("£","").replace(/^\s+|\s+$/g,'').match(/\d+.\d{2}/)[0])/Number(bt_itemQuanTrolley);var bask_item_val=bt_trolleyItems[i].getElementsByTagName("td")[tdNumber].innerHTML.replace(/<.*>/g,"").replace(/^\s+|\s+$/g,'').match(/\d+.\d{2}/)[0];bt_baskItems.push("&bask_name"+(i+1)+"="+bask_name.split('&').join('%26')+"&bask_each_val"+(i+1)+"="+bask_each_item_val+"&bask_items"+(i+1)+"="+bt_itemQuanTrolley+"&bask_val"+(i+1)+"="+bask_item_val+"&bask_image"+(i+1)+"=");}}
return"nourl=groceries-basket-event"+"&g_bask_event=groceries"+"&bask_total_items="+bt_totalItems+"&bask_total_val="+baskTotal+bt_baskItems.join("");}
catch(err){}})();}
else if(b.link_name!=="Add all products"){b.vendor_redeye_querystring=(function(){try{var bt_currDate=(function(){var fullDate=new Date();var twoDigitMonth=fullDate.getMonth()+1+"";if(twoDigitMonth.length==1)twoDigitMonth="0"+twoDigitMonth;var twoDigitDate=fullDate.getDate()+"";if(twoDigitDate.length==1)twoDigitDate="0"+twoDigitDate;return fullDate.getFullYear()+twoDigitMonth+twoDigitDate;})();if(document.getElementById("trolleyTableBody")){var bt_baskItems=[],bt_trolleyItems=document.getElementById("trolleyTableBody").getElementsByTagName("tr");for(var i=0;i<bt_trolleyItems.length;i++){if(i<5){var bt_itemQuanTrolley=(function(){var bt_itemQuan=bt_trolleyItems[i].getElementsByTagName("td")[0].getElementsByTagName("li");for(var l=0;l<bt_itemQuan.length;l++){if(bt_itemQuan[l].className=="inTrolley"){return bt_itemQuan[l].innerHTML.match(/\d+/)[0];}}})();var bask_each_val;bask_name=bt_trolleyItems[i].getElementsByTagName("td")[1].getElementsByTagName("a")[0].innerText.replace(/<.*>/g,"").replace(/^\s+|\s+$/g,'');bask_each_val=(Number(bt_trolleyItems[i].getElementsByTagName("td")[2].innerHTML.replace(/<.*>/g,"").replace("£","").replace(/^\s+|\s+$/g,'').match(/\d+.\d{2}/)[0])/Number(bt_itemQuanTrolley)).toFixed(2);bt_baskItems.push("&bask_name"+(i+1)+"="+bask_name.split('&').join('%26')+"&bask_each_val"+(i+1)+"="+bask_each_val+"&bask_items"+(i+1)+"="+bt_itemQuanTrolley+"&bask_val"+(i+1)+"="+bt_trolleyItems[i].getElementsByTagName("td")[2].innerHTML.replace(/<.*>/g,"").replace(/^\s+|\s+$/g,'').match(/\d+.\d{2}/)[0]+"&bask_image"+(i+1)+"=");}}}
else{bt_baskItems=[];}
var bt_divs=document.getElementsByTagName("div"),bt_prodPage="No",bt_prodName,bt_prodCat,bt_prodHier=[];for(var j=0;j<bt_divs.length;j++){if(bt_divs[j].className=="productSummary"){bt_prodPage="Yes";}}
if(document.getElementById("breadcrumbNav")){var bt_breadCrumbs=document.getElementById("breadcrumbNav").getElementsByTagName("li");for(var k=0;k<bt_breadCrumbs.length;k++){if(bt_breadCrumbs[k].className!==""){if(bt_breadCrumbs[k].getElementsByTagName("a")[0]===undefined){var breadCrumbs=bt_breadCrumbs[k].innerText.replace(/^\s+|\s+$/g,'').replace("<strong>","").replace("</strong>","");bt_prodHier.push(breadCrumbs.split('&').join('%26'));}
else{breadCrumbs=bt_breadCrumbs[k].getElementsByTagName("a")[0].innerText.replace(/^\s+|\s+$/g,'').replace("<span>","").replace("</span>","");bt_prodHier.push(breadCrumbs.split('&').join('%26'));}}}}
else{bt_prodHier.push("");}
if(digitalData.page.pageInfo.rendering==='web'){itemInTrolley=document.getElementById('itemsInTrolley').innerHTML;}
else{itemInTrolley="";}
return"nourl=groceries-basket-add"+"&bask_add=yes"+"&basket_cat="+bt_prodHier[bt_prodHier.length-1]+"&basket_hier="+bt_prodHier.join(">")+"&basket_domain=Groceries"+"&basket_timestamp="+bt_currDate+"&g_bask_event=groceries"+"&bask_total_items="+itemInTrolley+"&bask_total_val="+document.getElementById("trolleyTotal").innerHTML.replace("£","").replace(/^\s+|\s+$/g,'')+bt_baskItems.join("");}
catch(err){}})();}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['event_name'].toString().toLowerCase()=='addToBasketFromFavorites'.toLowerCase()){b.vendor_redeye_querystring=(function(){try{var bt_currDate=(function(){var fullDate=new Date();var twoDigitMonth=fullDate.getMonth()+1+"";if(twoDigitMonth.length==1)twoDigitMonth="0"+twoDigitMonth;var twoDigitDate=fullDate.getDate()+"";if(twoDigitDate.length==1)twoDigitDate="0"+twoDigitDate;return fullDate.getFullYear()+twoDigitMonth+twoDigitDate;})();bt_baskItems=window.btBaskItems;var bt_divs=document.getElementsByTagName("div"),bt_prodPage="No",bt_prodName,bt_prodCat,bt_prodHier=[];for(var j=0;j<bt_divs.length;j++){if(bt_divs[j].className=="productSummary"){bt_prodPage="Yes";}}
if(document.getElementById("breadcrumbNav")){var bt_breadCrumbs=document.getElementById("breadcrumbNav").getElementsByTagName("li");for(var k=0;k<bt_breadCrumbs.length;k++){if(bt_breadCrumbs[k].className!==""){if(bt_breadCrumbs[k].getElementsByTagName("a")[0]===undefined){var breadCrumbs=bt_breadCrumbs[k].innerText.replace(/^\s+|\s+$/g,'').replace("<strong>","").replace("</strong>","");bt_prodHier.push(breadCrumbs.split('&').join('%26'));}
else{breadCrumbs=bt_breadCrumbs[k].getElementsByTagName("a")[0].innerText.replace(/^\s+|\s+$/g,'').replace("<span>","").replace("</span>","");bt_prodHier.push(breadCrumbs.split('&').join('%26'));}}}}
else{bt_prodHier.push("");}
try{basketHier=bt_prodHier.join(">").trim().replace("\n","").replace(" ","").replace(" ","").replace(" ","").replace(" ","").replace(" ","").replace(" ","").replace(" ","").replace(" ","").replace(" ","").replace(" ","");}catch(err){basketHier="Favourites>Previous orders";}
var itemInTrolley;if(digitalData.page.pageInfo.rendering==='web'){itemInTrolley=document.getElementById('itemsInTrolley').innerHTML;}
else{itemInTrolley="";}
return"nourl=groceries-basket-add"+"&bask_add=yes"+"&basket_cat="+bt_prodHier[bt_prodHier.length-1]+"&basket_hier="+basketHier+"&basket_domain=Groceries"+"&basket_timestamp="+bt_currDate+"&g_bask_event=groceries"+"&bask_total_items="+itemInTrolley+"&bask_total_val="+document.getElementById("trolleyTotal").innerHTML.replace("£","").replace(/^\s+|\s+$/g,'')+bt_baskItems.join("");}
catch(err){}})();}}catch(e){utag.DB(e)}},function(a,b){try{if(1){try{if(("last_button_pressed"in b)&&(b.last_button_pressed.toLowerCase()==="log in")){b.ga_events_array=[{eventCategory:"Successful Login",eventAction:"Successful Login"}];document.cookie="last_button_track=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";}}catch(err){console.log("\n\nTealium Extension 219. Error:\n"+err);}}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['product_finding_method']!='undefined'&&typeof b['product_finding_method']!='undefined'&&b['product_finding_method']!='')){pfm=b.product_finding_method
var pfm_category;if(pfm.indexOf("favourites")==0){pfm_category="Favourites";}
else if(pfm.indexOf("search")==0){pfm_category="Search";}
else if(pfm.indexOf("forgottenFavourites")==0){pfm_category="Forgotten Favourites";}
else if(pfm.indexOf("shopping list Search")==0){pfm_category="Shopping List Search";}
else if(pfm.indexOf("trolley")==0){pfm_category="Trolley";}
else if(pfm.indexOf("Product Detail")==0){pfm_category="Product Detail";}
else if(pfm.indexOf("greatPrices")==0){pfm_category="Great Prices";}
else if(pfm.indexOf("peerius")==0){pfm_category="Peerius";}
else if(pfm.indexOf("hookLogic")==0){pfm_category="HookLogic";}
else if(pfm.indexOf("productUpsell")==0){pfm_category="Product Upsell";}
else if(pfm.indexOf("hierarchy")==0){pfm_category="Hierarchy";}
else if(pfm.indexOf("greatOffer")==0){pfm_category="Great Offers";}
else if(pfm.indexOf("productEspot")==0){pfm_category="Product Espot";}
else if(pfm.indexOf("SearchRedirect")==0){pfm_category="Search Redirect";}
else if(pfm.indexOf("replacement")==0){pfm_category="Replacement";}
else if(pfm.indexOf("importfav")==0){pfm_category="Import Favourites";}
else if(pfm.indexOf("discover")==0){pfm_category="Discover";}
else if(pfm.indexOf("crossSell")==0){pfm_category="Cross-Sell";}
else if(pfm.indexOf("upSell")==0){pfm_category="Upsell";}
else if(pfm.indexOf("nz")==0){pfm_category="Espot";}
else if(pfm.indexOf("mob_nz")==0){pfm_category="Espot";}
else if(pfm.indexOf("z:")==0){pfm_category="Espot";}
else if(pfm.indexOf("z_")==0){pfm_category="Espot";}
else if(pfm.indexOf("spotlight")==0){pfm_category="Search"}
else{pfm_category="(Other)";}
b.ga_pfm_category=pfm_category;}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(digitalData){if(digitalData.page&&digitalData.page.search){var multiSearchTerms=digitalData.page.search[0];b.multiSearchKeywords=multiSearchTerms.multiSearchKeywords;b.multiSearchNumber=multiSearchTerms.multiSearchNumber;}}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['new_page_template'].toString().toLowerCase()=='deliveryslots'.toLowerCase()){if(window.isBookDeliveryClickTrigged===undefined&&"new_page_template"in b&&b.new_page_template.toLowerCase()==="deliveryslots"){document.addEventListener('mousedown',function(event){var itemLink=event.target;var tbParent=null;var price="";var eventName="Book Delivery Slot Click";var deliveryType="";var deliveryGreenSlots="";var deliveryLocation="";var deliveryPrice="";var deliveryStatus="";var tDL=(typeof(b)!=="undefined")?b:utag.data;var arrLinkText=[];var isOkToTrack=false;var linkText=null;var bookingSlotDetails=null;var deliveryTime=null;var utagLinkParameters={};try{if(itemLink.innerText.trim().toLowerCase()!=="close"){deliveryType=("delivery_type"in tDL)?tDL.delivery_type:"";deliveryGreenSlots=("delivery_greenslots"in tDL)?tDL.delivery_greenslots:"";deliveryLocation=("delivery_location"in tDL)?tDL.delivery_location:"";deliveryPrice=("delivery_price"in tDL)?tDL.delivery_price:"";deliveryStatus=("delivery_status"in tDL)?tDL.delivery_status:"";if(tDL.rendering_reference==="web"){if(event.target.tagName.toLowerCase()==="a"){tbParent=itemLink.parentElement.parentElement.parentElement;if(tbParent.className.toLowerCase()==="allday morning"||tbParent.className.toLowerCase()==="allday evening"||tbParent.className.toLowerCase()==="allday afternoon"){linkText=itemLink.text.trim();bookingSlotDetails="";deliveryTime="";if(linkText.indexOf("£")>0){price=linkText.split("£")[1];if(price.indexOf(".")==-1){price=price.toString()+".0";}}
if((linkText.indexOf("Book delivery for ")===0)||(linkText.indexOf("Click and collect for ")===0)){if(linkText.indexOf("Book delivery for ")===0){linkText=linkText.replace("Book delivery for ","");}
if(linkText.indexOf("Click and collect for ")===0){linkText=linkText.replace("Click and collect for ","");}
if(linkText.indexOf(", ")>0){arrLinkText=linkText.split(", ");if(arrLinkText.length==3){if(arrLinkText[1].length>7&&arrLinkText[1].indexOf("between ")===0){deliveryTime=arrLinkText[1].replace("between ","");}
bookingSlotDetails=arrLinkText[0]+" "+deliveryTime;}}}else{bookingSlotDetails=linkText;}
isOkToTrack=true;}}}else if(tDL.rendering_reference==="mobileweb"){linkText=itemLink.text;for(i=0;i<=30;i++){linkText=linkText.replace("\n","");}
linkText=linkText.trim();for(var i=0;i<=1000;i++){linkText=linkText.replace(" ","");}
if(linkText.indexOf("Availablefor£")>0){arrLinkText=linkText.split("Availablefor£");price=arrLinkText[1];if(price.indexOf(".")==-1){price=price.toString()+".0";}
deliveryTime=arrLinkText[0];deliveryTime=deliveryTime.split("-")[0]+" - "+deliveryTime.split("-")[1];var currentDay=document.getElementsByClassName("currentDay");if(currentDay.length>=1){arrLinkText=currentDay[0].outerText.split(" ");var weekDay=arrLinkText[0];var day=arrLinkText[1];var month=arrLinkText[2];var year=arrLinkText[3];switch(weekDay.toLowerCase()){case"sun":weekDay="Sunday";break;case"mon":weekDay="Monday";break;case"tue":weekDay="Tuesday";break;case"wed":weekDay="Wednesday";break;case"thu":weekDay="Thursday";break;case"fri":weekDay="Friday";break;case"sat":weekDay="Saturday";break;}
switch(month.toLowerCase()){case"jan":month="January";break;case"feb":month="February";break;case"mar":month="March";break;case"apr":month="April";break;case"may":month="May";break;case"jun":month="June";break;case"jul":month="July";break;case"aug":month="August";break;case"sep":month="September";break;case"oct":month="October";break;case"nov":month="November";break;case"dec":month="December";break;}
bookingSlotDetails=weekDay+" "+day+" "+month+" "+year+" "+deliveryTime;isOkToTrack=true;}}}
if(isOkToTrack){utagLinkParameters={"event_name":eventName,"delivery_option":"standard","delivery_type":deliveryType,"order_delivery_slot":bookingSlotDetails,"booking_slot_price":price,"delivery_greenslots":deliveryGreenSlots,"delivery_location":deliveryLocation,"delivery_price":deliveryPrice,"delivery_status":deliveryStatus,"page_name_identifier":"Delivery reserved"};utag.link(utagLinkParameters);}}}catch(err){console.warn("Tealium extension 251: Error.\n"+err);}},false);window.isBookDeliveryClickTrigged=true;}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){var profileInfo=digitalData.user.profile.profileInfo;if(profileInfo.isUkBilling&&(b.page_section==="checkout"||b.page_section==="my account")){b.is_uk_billing=profileInfo.isUkBilling;}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b['aw_feed_language']='EN';b['aw_merchant_id']='113678945';b['_ccountry']='GB'}}catch(e){utag.DB(e)}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev["all"]!="undefined"){if(a==="remote_api"){utag.DB("Remote API event suppressed.");return;}
if(u.data_source){b.tealium_datasource=u.data_source;}
u.make_enrichment_request=false;for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};if(!u.is_in_sample_group(b)){return false}
u.get_performance_timing(b);for(var i=0;i<u.server_list.length;i++){if(b["cp.utag_main_dc_region"]){u.region=b["cp.utag_main_dc_region"];u.server_list[i]=u.server_list[i].replace("datacloud.","datacloud-"+u.region+".");u.server_list[i]=u.server_list[i].replace("collect.","collect-"+u.region+".");}
if(u.enrichment_enabled[i]!==false){u.enrichment_enabled[u.server_list[i]]=true}}
if(u.server_list.length>1){u.profile_specific_vid=1;}
u.data=utag.datacloud||{};u.data["loader.cfg"]={};for(d in utag.loader.GV(utag.loader.cfg)){if(utag.loader.cfg[d].load&&utag.loader.cfg[d].send){utag.loader.cfg[d].executed=1;}else{utag.loader.cfg[d].executed=0;}
u.data["loader.cfg"][d]=utag.loader.GV(utag.loader.cfg[d]);}
u.data.data=b;for(d in u.data.data){if((d+'').indexOf("qp.")==0){u.data.data[d]=encodeURIComponent(u.data.data[d]);}else if((d+'').indexOf("va.")==0){delete u.data.data[d]}}
if(!b["cp.utag_main_dc_event"]){b["cp.utag_main_dc_visit"]=(1+(b["cp.utag_main_dc_visit"]?parseInt(b["cp.utag_main_dc_visit"]):0))+'';}
b["cp.utag_main_dc_event"]=(1+(b["cp.utag_main_dc_event"]?parseInt(b["cp.utag_main_dc_event"]):0))+'';utag.loader.SC("utag_main",{"dc_visit":b["cp.utag_main_dc_visit"],"dc_event":b["cp.utag_main_dc_event"]+";exp-session"});utag.data["cp.utag_main_dc_visit"]=b["cp.utag_main_dc_visit"];utag.data["cp.utag_main_dc_event"]=b["cp.utag_main_dc_event"];var dt=new Date();u.data.browser={};try{u.data.browser["height"]=window.innerHeight||document.body.clientHeight;u.data.browser["width"]=window.innerWidth||document.body.clientWidth;u.data.browser["screen_height"]=screen.height;u.data.browser["screen_width"]=screen.width;u.data.browser["timezone_offset"]=dt.getTimezoneOffset();}catch(e){utag.DB(e)}
u.data["event"]=a+'';u.data["post_time"]=dt.getTime();if(u.data_enrichment=="frequent"||u.data_enrichment=="infrequent"){u.visit_num=b["cp.utag_main_dc_visit"];if(parseInt(u.visit_num)>1&&b["cp.utag_main_dc_event"]=="1"){u.enrichment_polling=2;}
try{u.va_update=parseInt(localStorage.getItem("tealium_va_update")||0);}catch(e){utag.DB(e)}
u.visitor_id=u.visitor_id||b.tealium_visitor_id||b['cp.utag_main_v_id'];if((u.data_enrichment=="frequent"&&!(u.visit_num=="1"&&b["cp.utag_main_dc_event"]=="1"))||(u.data_enrichment=="infrequent"&&parseInt(u.visit_num)>1&&parseInt(b["cp.utag_main_dc_event"])<=5&&u.visit_num!=u.va_update)){u.make_enrichment_request=true;}else if(b._corder){u.make_enrichment_request=true;u.enrichment_polling=3;u.enrichment_polling_delay=4000;}
u.visitor_service_request=function(t,server){var s="https://"+u.server_prefix+"visitor-service"+(u.region?"-"+u.region:"").replace(/[^-A-Za-z0-9+_.]/g,"")+"."+u.server_domain;var p=u.get_account_profile(server);(function(p){var prefix="tealium_va";var key="_"+p[1]+"_"+p[2];utag.ut["writeva"+p[2]]=function(o){utag.DB("Visitor Attributes: "+prefix+key);utag.DB(o)
var str=JSON.stringify(o);if(str!="{}"&&str!=""){try{localStorage.setItem('tealium_va_update',utag.data["cp.utag_main_dc_visit"]);localStorage.setItem(prefix,str);localStorage.setItem(prefix+key,str);}catch(e){utag.DB(e)}
if(typeof tealium_enrichment=="function"){tealium_enrichment(o,prefix+key);}}}}(p.slice(0)))
var vid=u.visitor_id;if(u.profile_specific_vid==1){vid+=p[2];}
utag.ut.loader({id:"tealium_visitor_service_65"+p[2],src:s+"/"+p[1]+"/"+p[2]+"/"+vid.replace(/\?callback=.*/g,"")+"?callback=utag.ut%5B%22writeva"+p[2]+"%22%5D&rnd="+t});}
u.do_enrichment=function(server,enrichment_polling,enrichment_polling_delay){if(typeof utag.ut.loader!="undefined"){for(var i=0;i<enrichment_polling;i++){setTimeout(function(){u.visitor_service_request((new Date).getTime(),server)},i*enrichment_polling_delay+1);}}}}
var json_string;var regExpReplace=new RegExp(u.visitor_id,"g");if(window.FormData){function postData(server_index,enrichment_polling,enrichment_polling_delay){if(server_index+1>u.server_list.length){return;}
var xhr=new XMLHttpRequest();var server=u.server_list[server_index];var formData=new FormData();xhr.addEventListener('readystatechange',function(){if(xhr.readyState===3){try{u.region=xhr.getResponseHeader("X-Region")||u.region||"";}catch(res_error){utag.DB(res_error);u.region=u.region||"";}
if(u.region)utag.loader.SC("utag_main",{"dc_region":u.region+";exp-session"});utag.DB("dc_region:"+u.region);}else if(xhr.readyState===4){postData(server_index+1,enrichment_polling,enrichment_polling_delay);if(u.make_enrichment_request&&u.enrichment_enabled[server])u.do_enrichment(server,enrichment_polling,enrichment_polling_delay);}});xhr.open('post',u.server_list[server_index],true);xhr.withCredentials=true;json_string=JSON.stringify(u.data);if(u.profile_specific_vid==1){json_string=json_string.replace(regExpReplace,u.visitor_id+u.get_account_profile(server)[2]);}
formData.append("data",json_string);xhr.send(formData);}
postData(0,u.enrichment_polling,u.enrichment_polling_delay);}else{for(var i=0;i<u.server_list.length;i++){(function(i,enrichment_polling,enrichment_polling_delay){var server=u.server_list[i];setTimeout(function(){json_string=JSON.stringify(u.data);if(u.profile_specific_vid==1){json_string=json_string.replace(regExpReplace,u.visitor_id+u.get_account_profile(server)[2]);}
var img=new Image();img.src=server+'?data='+encodeURIComponent(json_string);if(u.make_enrichment_request&&u.enrichment_enabled[server])u.do_enrichment(server,enrichment_polling,enrichment_polling_delay);},i*700);}(i,u.enrichment_polling,u.enrichment_polling_delay))}}}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('65','sainsburys.groceries');}catch(e){utag.DB(e)}
