//tealium universal tag - utag.94 ut4.0.201812201455, Copyright 2018 Tealium.com Inc. All Rights Reserved.
var _uxa=_uxa||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.scriptrequested=false;u.map={"page_section":"custom.1.Page Section","page_category":"custom.2.Page Category","page_subcategory":"custom.3.Page SubCategory","user_status":"custom.4.login_status","shopping_mode":"custom.5.Shopping Mode","order_total":"order_total","order_id":"order_id","ContentSquare_id_project":"id_project","new_page_template":"custom.6.Page Template"};u.extend=[function(a,b,c){for(c in utag.loader.GV(b)){try{b[c]=(b[c]instanceof Array||b[c]instanceof Object)?b[c]:b[c].toString().toLowerCase()}catch(e){}}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"base_url":"//t.contentsquare.net/uxa/##utag_id_project##.js","id_project":"396640724211a","custom":{},"path":"","product_id":[],"product_name":[],"product_sku":[],"product_category":[],"product_quantity":[],"product_unit_price":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("custom.")===0){u.data.custom[[e[f].substr(7)]]=b[d];}else{u.data[e[f]]=b[d];}}}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_total=u.data.order_total||b._ctotal||"";u.data.base_url=u.data.base_url.replace("##utag_id_project##",u.data.id_project);u.data.path=u.data.path||location.pathname+location.hash.replace("#","?__");var custom,customVar;for(custom in u.data.custom){if(u.data.custom.hasOwnProperty(custom)&&custom!==""){customVar=custom.split(".");_uxa.push(["setCustomVariable",customVar[0],customVar[1],u.data.custom[custom],3]);}}
if(a==="view"){_uxa.push(["trackPageview",u.data.path]);}else{_uxa.push(["setPath",u.data.path]);}
if(u.data.order_id){_uxa.push(["ecommerce:addTransaction",{"id":u.data.order_id,"revenue":u.data.order_total,"shipping":u.data.order_shipping,"tax":u.data.order_tax}]);_uxa.push(["ecommerce:send"]);}
if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":null,"loc":"script","id":"utag_94"});}
}};utag.o[loader].loader.LOAD(id);}("94","sainsburys.groceries"));}catch(error){utag.DB(error);}
