//tealium universal tag - utag.179 ut4.0.201901101232, Copyright 2019 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader,u){u=utag.o[loader].sender[id]={};u.ev={'view':1,'link':1};u.qsp_delim="&";u.kvp_delim="=";u.data={};u.base_url="//reporting.sainsburys-online.com/cgi-bin/rr/blank.gif?";u.map={};u.extend=[function(a,b){try{if(1){if(b.page_name==="groceries:mynectarcard"&&b["cp.redeyeupdate"]==="st_nectar"){var nectarNumber=b['cp.st_nectar'];document.cookie="redeyeupdate=false;path=/;domain="+utag.cfg.domain+";expires=";document.cookie='st_nectar=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/;';b.vendor_redeye_querystring="nourl="+location.hostname+location.pathname+"&nectar_card_add="+((b['cp.st_nectar'])?"Yes&nec_num="+nectarNumber:"No");}
else if(b["cp.bt_delSlot"]!==""&&b.booking_event==="delivery"){var bt_return=encodeURI("nourl=groceries-delivery-confirm"+"&g_delivery_confirm=yes"+"&g_delivery_time="+b["cp.bt_delSlot"].split("|")[0]+"&g_delivery_charge="+b.booking_slot_cost);document.cookie='bt_delSlot=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/;';b.vendor_redeye_querystring=bt_return;}
else if((document.getElementById('voucher')&&document.getElementById("voucher").style.display!="none")||(b.page_event==="order review"&&b.page_name_identifier==="order review")){if(b["cp.bt_vCode"]){var bt_voucherCode=b["cp.bt_vCode"].split("|");var bt_cookDate=new Date();bt_cookDate.setTime(bt_cookDate.getTime()+(30*24*60*60*1000));bt_voucherCode.pop();document.cookie="bt_vCode="+bt_voucherCode+"; expires="+bt_cookDate+";path=/;";}
b.vendor_redeye_querystring="nourl=groceries-checkout-confirm-order&g_checkout_confirm=yes";}
else if(document.title.indexOf("404")>-1){b.vendor_redeye_querystring="nourl=error-experienced&error_code=404";}
else if(b["cp.bt_regDetails"]&&(document.referrer.indexOf("QuickRegistrationFormView")>-1||location.pathname.indexOf("PostcodeCheckView")>-1||document.referrer.indexOf("/UserRegistrationAdd")>-1||document.referrer==="")&&document.title!="Register"||b["cp.redeyeupdate"]=="bt_regDetails"){document.cookie="redeyeupdate=false;path=/;domain="+utag.cfg.domain+";expires=";var bt_cookie=b["cp.bt_regDetails"].split("|");var bt_return="nourl=groceries-register-confirm"+"&rg_conf=groceries"+"&title="+bt_cookie[0]+"&firstname="+bt_cookie[1]+"&lastname="+bt_cookie[2]+"&email="+bt_cookie[3]+"&emailpermit="+bt_cookie[4]+"&rg_domain=groceries";if(b["cp.st_nectar"]&&b["cp.st_nectar"]!="|"){var nectarNumber=b['cp.st_nectar'];bt_return+="&nectar_card_add=yes"+"&nectar_no="+nectarNumber;document.cookie='st_nectar=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/;';}
else{bt_return+="&nectar_card_add=no";}
document.cookie='bt_regDetails=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/;';b.vendor_redeye_querystring=encodeURI(bt_return);}
else if(b["cp.bt_userEmail"]!==undefined&&(("last_button_pressed"in b)&&(b.last_button_pressed.toLowerCase()==="log in")||document.referrer.indexOf("/LogonView/Password")>-1)){document.cookie='bt_userEmail=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/;';b.vendor_redeye_querystring="nourl=groceries-log-in&email="+b["cp.bt_userEmail"];}
else{b.vendor_redeye_querystring="nourl="+location.hostname+location.pathname;document.cookie='bt_userEmail=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/;';}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||typeof u.ev.all!="undefined"){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};var c,d,e,f;c=b.vendor_redeye_querystring?b.vendor_redeye_querystring.split('&'):[];var xhttp=new XMLHttpRequest();xhttp.open("POST",u.base_url,true);xhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhttp.send(c.join(u.qsp_delim));}}
utag.o[loader].loader.LOAD(id);})('179','sainsburys.groceries');}catch(e){}
